name: Azure Tests
on:
  push:
    paths:
      - 'azure/tf/**'
      - '.github/workflows/azure-test.yml'
  pull_request:
    paths:
      - 'azure/tf/**'
      - '.github/workflows/azure-test.yml'
jobs:
  test-azure:
    uses: ./.github/workflows/terraform-ruw.yml
    with:
      working_directory: azure/tf
      tflint_args: --var 'tags={"foo":"bar"}'
    # This is used so that the reusable workflow can inherit repo secrets for auth to cloud providers.
    secrets: inherit
